oopapidocs: Abstract::MetaDataLoader Class Reference
Abstract::MetaDataLoader Class Reference
Abstract Interface for loading metadata from files.
#include <abstractmetadataloader.h>
Signals
void fetched (const MetaDataValue &mdv)
Emitted when metadata has been fetched by this object.
Public Member Functions
virtual MetaDataLoader * clone (QObject *parent=0)=0
Returns another instance of the same type.
virtual void get (QString path)=0
non-blocking method that fetches metadata.
Static Public Member Functions
static MetaDataLoader * instance ()
Detailed Description
Abstract Interface for loading metadata from files.
Create a concrete instance and add it as a child to qApp, and you can retrieve it via the abstract instance() method here.
Definition at line 13 of file abstractmetadataloader.h.
Member Function Documentation
virtual void Abstract::MetaDataLoader::get (QString path) [pure virtual]
non-blocking method that fetches metadata.
A fetched() signal is emitted when metadata is ready.
Implemented in Phonon::MetaDataLoader, and TagLib::MetaDataLoader.
Referenced by MetaDataTable::hasMetaData().
MetaDataLoader * MetaDataLoader::instance () [static]
Returns:
the first instance found of MetaDataLoader that is a child of qApp
Reimplemented in Phonon::MetaDataLoader, and TagLib::MetaDataLoader.
Definition at line 6 of file abstractmetadataloader.cpp.
Referenced by MetaDataLoaderProgressWidget::MetaDataLoaderProgressWidget(), and MetaDataTable::MetaDataTable().
The documentation for this class was generated from the following files:
docs/src/libs/metadata/abstractmetadataloader.h
docs/src/libs/metadata/abstractmetadataloader.cpp