oopapidocs: StdinReader Class Reference
StdinReader Class Reference
A simple I/O interface for reading properties of DataObjects from standard input.
#include <stdinreader.h>
Static Public Member Functions
static bool readProperties (DataObject *ptr)
Prompt to cout read each property from stdin, check against constraints, reprompt if invalid.
Detailed Description
A simple I/O interface for reading properties of DataObjects from standard input.
Will use input constraints if any were set.
Author:
Alan Ezust
Definition at line 16 of file stdinreader.h.
Member Function Documentation
bool StdinReader::readProperties (DataObject * ptr) [static]
Prompt to cout read each property from stdin, check against constraints, reprompt if invalid.
Parameters:
ptr address of object to set properties read from user.
Returns:
true if successful (should always be true since current version infinitely retries.)
Definition at line 12 of file stdinreader.cpp.
References DataObject::className(), DataObject::property(), and DataObject::setProperty().
The documentation for this class was generated from the following files:
docs/src/libs/dataobjects/stdinreader.h
docs/src/libs/dataobjects/stdinreader.cpp