oopapidocs: DocbookDoc Class Reference
DocbookDoc Class Reference
A docbook/XML document.
#include <docbookdoc.h>
Public Member Functions
Element title (QString title, Element parent=Element())
Element bridgehead (QString title)
Element chapter (QString title)
Element xref (QString id)
Element xrefP (QString id)
Element section (QString title)
Element appendix (QString title)
Element bold (QString boldText)
QString getTitle (Element el) const
Element formalpara (QString title, QString text)
Element para (QString text)
Element simplesect (QString titleStr)
Static Public Member Functions
static void setRole (Element el, QString role)
Detailed Description
A docbook/XML document.
Author:
Alan Ezust
Definition at line 18 of file docbookdoc.h.
Member Function Documentation
Element DocbookDoc::appendix (QString title)
Returns:
a new appendix
Definition at line 55 of file docbookdoc.cpp.
References title().
Element DocbookDoc::bold (QString boldText)
Returns:
a parentless but of bold text
Definition at line 93 of file docbookdoc.cpp.
References setRole().
Element DocbookDoc::bridgehead (QString title)
Returns:
a new bridgehead element child
Definition at line 10 of file docbookdoc.cpp.
References title().
Element DocbookDoc::chapter (QString title)
Returns:
a new <chapter> element, with given title, as a child of the root element
Definition at line 25 of file docbookdoc.cpp.
References title().
Element DocbookDoc::formalpara (QString title, QString text)
Returns:
a new paragraph with a title, as a child of the most recently created chapter or section
Definition at line 83 of file docbookdoc.cpp.
References title().
QString DocbookDoc::getTitle (Element el) const
Returns:
the title of the corresponding element, if there is one.
Definition at line 44 of file docbookdoc.cpp.
Referenced by DocbookWalker::heading().
Element DocbookDoc::para (QString text)
Returns:
an ordinary paragraph
Definition at line 34 of file docbookdoc.cpp.
Referenced by xrefP().
Element DocbookDoc::section (QString title)
Returns:
a new section, as a child of the most recently created chapter.
Definition at line 62 of file docbookdoc.cpp.
References title().
void DocbookDoc::setRole (Element el, QString role) [static]
Parameters:
el An element for which you want to set an attribute
role - the condition you wish to set
Definition at line 102 of file docbookdoc.cpp.
Referenced by bold().
Element DocbookDoc::simplesect (QString titleStr)
Returns:
a titled simplesect element
Definition at line 125 of file docbookdoc.cpp.
References title().
Element DocbookDoc::title (QString title, Element parent = Element())
Returns:
a new <title> element with parent set to parent.
Definition at line 16 of file docbookdoc.cpp.
Referenced by appendix(), bridgehead(), chapter(), formalpara(), section(), and simplesect().
Element DocbookDoc::xref (QString id)
Returns:
a simple xref element
Definition at line 107 of file docbookdoc.cpp.
Referenced by xrefP().
Element DocbookDoc::xrefP (QString id)
Returns:
an xref in parantheses in a para
Definition at line 113 of file docbookdoc.cpp.
References para(), and xref().
The documentation for this class was generated from the following files:
docs/src/libs/docbook/docbookdoc.h
docs/src/libs/docbook/docbookdoc.cpp